import test from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {startServer} from '../../src/v3/server.mjs';
test('ordinary web form chooses Excel, previews exact copy and requires publish confirmation',async()=>{
  let saved,started=0;
  const state={config:{copyFile:'C:/test.xlsx',accounts:[{id:'a',expectedIdentity:'123',materialDir:'C:/videos'}]},copyCount:20,run:{phase:'IDLE',message:'就绪',busy:false},records:[],preview:null};
  const service={getState:async()=>state,saveConfig:async input=>{saved=input;},preview:async()=>{state.preview={digest:'d',jobs:[{id:'j',expectedIdentity:'123',path:'C:/videos/fzq_A_1_KOC1.mp4',copyId:'001',description:'正文\n#牙膏#生活\nfzq_A_1'}]};},start:async input=>{assert.equal(input.digest,'d');assert.equal(input.confirmRemoteWrite,true);started++;}};
  const host=await startServer(service,{assetDirectory:new URL('../../src/ordinary-public/',import.meta.url)});
  service.importPreview=async()=>({accounts:[{expectedIdentity:'123',operatorId:'运营甲',editor:'fzq',koc:'KOC1',materialDir:'C:/videos',enabled:true},{expectedIdentity:'456',operatorId:'运营甲',editor:'fzq',koc:'KOC2',materialDir:'C:/videos2',enabled:false}]});
  const browser=await chromium.launch({headless:true,channel:'chromium'});
  try{
    const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto(host.url);await page.locator('#accounts input').first().waitFor();
    await page.reload();await page.locator('#accounts input').first().waitFor({timeout:5000});
    assert.equal(started,0,'refresh must restore authentication without publishing');
    assert.equal(await page.locator('.sidebar nav a').count(),4);
    await page.getByRole('link',{name:/基础资料/}).click();
    assert.equal(await page.getByRole('link',{name:/基础资料/}).getAttribute('aria-current'),'location');
    assert.equal(await page.locator('#count-candidates').innerText(),'0');
    await page.locator('#excel').setInputFiles({name:'文案.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from('fixture')});
    await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已保存'));
    assert.equal(saved.excel.name,'文案.xlsx');assert.equal(Buffer.from(saved.excel.base64,'base64').toString(),'fixture');
    await page.locator('#add-account').click();
    assert.equal(await page.locator('.account-row').count(),2);
    await page.locator('.account-row').last().getByRole('button',{name:'移除未保存账号'}).click();
    assert.equal(await page.locator('.account-row').count(),1);
    assert.equal(await page.locator('[data-field="expectedIdentity"]').getAttribute('readonly'),'');
    await page.getByText('Excel 批量导入账号',{exact:true}).click();
    await page.locator('#account-excel').setInputFiles({name:'accounts.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from('fixture')});
    await page.locator('#import-accounts').click();await page.locator('#account-import-result strong').first().waitFor();
    assert.equal(await page.locator('#account-import-result strong').first().innerText(),'更新 · 123');
    await page.locator('#apply-accounts').click();assert.equal(await page.locator('.account-row').count(),2);
    assert.equal(await page.locator('.account-row').first().getAttribute('data-account'),'a');
    assert.equal(await page.locator('.account-row').last().locator('[data-field="enabled"]').inputValue(),'false');
    let aiCalls=0;service.aiPreview=async input=>{assert.equal(input.consent,true);assert.equal(input.instruction,'选择生活文案');aiCalls++;state.preview={digest:'d',jobs:[{id:'j',expectedIdentity:'123',path:'C:/videos/fzq_A_1_KOC1.mp4',copyId:'001',description:'AI 正文',aiReason:'符合生活主题'}]};return state.preview;};
    await page.locator('#ai-instruction').fill('选择生活文案');await page.locator('#ai-preview').click();
    await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('先勾选'));assert.equal(aiCalls,0);
    await page.locator('#ai-consent').check();await page.locator('#ai-preview').click();
    await page.getByText('AI 选择理由：符合生活主题',{exact:true}).waitFor();assert.equal(aiCalls,1);assert.equal(started,0);
    await page.locator('#scan').click();await page.waitForFunction(()=>document.querySelector('#preview .copy')?.textContent==='正文\n#牙膏#生活\nfzq_A_1');assert.equal(await page.locator('#preview .copy').innerText(),'正文\n#牙膏#生活\nfzq_A_1');
    page.once('dialog',d=>d.dismiss());await page.locator('#publish').click();assert.equal(started,0);
    page.once('dialog',d=>d.accept());await page.locator('#publish').click();await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已开始'));
    assert.equal(started,1);assert.deepEqual(errors,[]);
    state.run={phase:'DONE',message:'本轮结束，有记录需要核对',busy:false,outcomes:[{status:'UNKNOWN'}]};
    await page.waitForFunction(()=>document.querySelector('#notice').textContent==='本轮结束，有记录需要核对');
    assert.equal(await page.locator('#notice').getAttribute('class'),'notice error');
    await page.setViewportSize({width:1440,height:1000});
    await page.getByRole('link',{name:/发布总览/}).click();
    await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
    await page.screenshot({path:'demo-output/ordinary-sidebar-desktop.png'});
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  }finally{await browser.close();await host.close();}
});
